[package]
name = "atomichorizon/order"
version = "3.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
AnimNation = "michaeldougal/animnation@1.13.1"
Cmdr = "evaera/cmdr@1.12.0"
Component = "sleitnick/component@2.4.8"
GamebeastSDK = "gamebeast-gg/gamebeast@0.9.0"
Signal = "sleitnick/signal@2.0.3"
TopbarPlus = "1foreverhd/topbarplus@3.4.0"
Trove = "sleitnick/trove@1.8.0"
